#theme: jekyll-theme-primer
#theme: jekyll-theme-minimal
theme: jekyll-theme-tactile
title: Aivclab
description: Projects
logo: /uploads/aivclab.svg
#show_downloads: true
#google_analytics:
#theme: jekyll-theme-minimal

# Build settings
defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default" # this ensures all content renders with layouts/default.html

plugins:
  - jekyll-feed
  - jekyll-menus
