---
label: default
hide_body: false
fields:
- name: layout
  type: text
  config:
    required: false
  label: Layout
- name: a
  type: blocks
  label: a
  template_types:
  - navigation-header
  config:
    min: 
    max: 
